{
 "title": "Пельменная",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Задержка к бэкенду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(response_timing_ms_count{}[1m])"
    }
   ]
  },
  {
   "title": "Доступность бэкенда",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    { "expr": "up{}" }
   ]
  },
  {
   "title": "Количество запросов к бэкенду ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(requests_count{}[1m])" }
   ]
  }
 ]
}