# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  annotations:
    meta.helm.sh/release-name: sausage
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: >-
    replace_from_gitlab
type: kubernetes.io/dockerconfigjson