# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  annotations:
    meta.helm.sh/release-name: momo-store
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: |
    {{ .Values.dockerconfigjson }}
#   .dockerconfigjson: ***REMOVED***
type: kubernetes.io/dockerconfigjson