# values.yaml
backend: # Это имя чарта из dependencies
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image: gitlab.praktikum-services.ru:5050/std-012-056/momo-store/momo-backend
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "125Mi"
      cpu: 0.1
    limits:
      memory: "200Mi"
      cpu: 0.2
  environment: production


frontend:
  image: gitlab.praktikum-services.ru:5050/std-012-056/momo-store/momo-frontend
  tag: latest
  replicas: 1
  ingresshost: "130.193.37.242.nip.io"
  resources:
    requests:
      memory: "125Mi"
      cpu: 0.1
    limits:
      memory: "300Mi"
      cpu: 0.5
  environment: production