backend:
  image: gitlab.praktikum-services.ru:5050/std-012-056/momo-store/momo-backend
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "50Mi"
      cpu: 0.1
    limits:
      memory: "100Mi"
      cpu: 0.2
  environment: production


frontend:
  image: gitlab.praktikum-services.ru:5050/std-012-056/momo-store/momo-frontend
  tag: latest
  replicas: 1
  ingresshost: "130.193.37.242.nip.io"
  resources:
    requests:
      memory: "100Mi"
      cpu: 0.1
    limits:
      memory: "250Mi"
      cpu: 0.5
  environment: production