grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 15
          editable: true
          options:
            path: /var/lib/grafana/default/dashboards
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:9090
          access: proxy
          isDefault: true
  dashboards:
    default:
      kubernetes:
        json: |
${indent(10, file(".grafana/dashboards/kubernetes.json"))}