grafana:
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /usr/share/grafana/conf/provisioning/dashboards

  dashboards:
    default:
      kubernetes:
        json: |
          ${indent(8, file("./dashboards/Momo-store.json"))}

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http:prometheus:9090