apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: grafana-letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: artamokhin1@yandex.ru
    privateKeySecretRef:
      name: grafana-letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
